DROP TABLE IF EXISTS PassengerBooking CASCADE;
DROP TABLE IF EXISTS BookingPackage CASCADE;

DROP TABLE IF EXISTS Booking CASCADE;
DROP TABLE IF EXISTS Ticket CASCADE;
DROP TABLE IF EXISTS Seat CASCADE;
DROP TABLE IF EXISTS CodeShare CASCADE;

DROP TABLE IF EXISTS Passenger CASCADE;
DROP TABLE IF EXISTS Package CASCADE;
DROP TABLE IF EXISTS Flight CASCADE;